### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by macropin** [frankwiles/django-admin-views#11]
Please roll a new PyPi release. The last release to PyPi was on 2012-11-25. The latest head incorporates fixes that are required to make this useful with new Django versions.

**Comment by JJWTimmer** [comment]
please release this

**Comment by frankwiles** [comment]
So sorry for the delays on this.  Just uploaded new version with all the recent (well not that recent) fixes https://pypi.python.org/pypi/django-admin-views/0.2.0
