### ISSUE TITLE
Templatetag formating

### ISSUE THREAD

**Issue by synw** [frankwiles/django-admin-views#29]
Would it be possible to have a templatetag that does not output a table row but just the link? I am using a custom `admin/index.html` where there is no table: it would be nice to have a raw output from the templatetag.

**Comment by frankwiles** [comment]
It doesn't exist right now, but it wouldn't be hard to create.  In fact you could simply copy the code from admin-views's templatetag, specifically `admin_views.templatetags.admin_views.get_admin_views` and adjust the output to be whatever you want.
